---
# tasks file for cvp.refresh

- name: "collect CVP Facts"
  tags:
    - sync
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Refresh Shared Configlet Data"
  tags:
    - sync
  include_vars:
     file: './generated_vars/common_configlets/master.yml'
     name: 'shared_configlets'
  delegate_to: localhost

- name: 'Refresh Shared configlet files for CVP'
  tags:
    - sync
  template:
    src: "./roles/cvp.provision/templates/template.shared_configlets.j2"
    dest: './generated_vars/cvp_servers/{{inventory_hostname}}_shared.yml'
  delegate_to: localhost
  run_once: False

- name: "Load refreshed CVP shared Configlet information"
  tags:
    - sync
  include_vars: './generated_vars/cvp_servers/{{inventory_hostname}}_shared.yml'
  delegate_to: localhost

- name: 'Update Shared configlets on CVP Servers.'
  tags:
    - sync
  arista.cvp.cv_configlet:
    cvp_facts: "{{CVP_FACTS.ansible_facts}}"
    configlets: "{{CVP_CONFIGLET}}"
    configlet_filter: ["shared"]
