---
# tasks file for ztp-setup
- name: 'Generate DHCPd configuration file'
  become: true
  template:
    src: 'dhcpd.conf.j2'
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
  notify: "restart dhcpd"

- name: Check & activate DHCP service
  service:
    name: dhcpd
    enabled: yes
    state: started
